//
//  VioletColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

#if os(macOS)
/// Autogenerated from [Figma](https://www.figma.com/design/lowzSNK3XysASQ1urGCZFp/Browser-Color-Themes?node-id=504-17677&m=dev)
struct VioletColorPalette: SharedColorPaletteDefinition {
    static let accentAltContentPrimary = DynamicColor(lightHex: 0x2b097a, darkHex: 0xf5f5fe)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x2c0a7b, lightOpacityHex: 0xb2, darkHex: 0xf5f5fe, darkOpacityHex: 0xb2)
    static let accentAltContentTertiary = DynamicColor(lightHex: 0x2c0a7b, lightOpacityHex: 0x7f, darkHex: 0xf5f5fe, darkOpacityHex: 0x7f)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0xa280ff, lightOpacityHex: 0x33, darkHex: 0xa280ff, darkOpacityHex: 0x33)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0xa280ff, lightOpacityHex: 0x1e, darkHex: 0xa280ff, darkOpacityHex: 0x1e)
    static let accentAltPrimary = DynamicColor(lightHex: 0xc6b2ff, darkHex: 0x5c17e5)
    static let accentAltSecondary = DynamicColor(lightHex: 0xa17fff, darkHex: 0x470fbf)
    static let accentAltTertiary = DynamicColor(lightHex: 0x8f69fb, darkHex: 0x3b0da6)
    static let accentAltTextPrimary = DynamicColor(lightHex: 0x470fbf, darkHex: 0xc6b2ff)
    static let accentAltTextSecondary = DynamicColor(lightHex: 0x3b0da6, darkHex: 0xa17fff)
    static let accentAltTextTertiary = DynamicColor(lightHex: 0x2b097a, darkHex: 0x8f69fb)
    static let accentContentPrimary = DynamicColor(lightHex: 0xf5f5fe, darkHex: 0x030109)
    static let accentContentSecondary = DynamicColor(lightHex: 0xf5f5fe, lightOpacityHex: 0xb2, darkHex: 0x030109, darkOpacityHex: 0xb2)
    static let accentContentTertiary = DynamicColor(lightHex: 0xf5f5fe, lightOpacityHex: 0x7f, darkHex: 0x030109, darkOpacityHex: 0x7f)
    static let accentGlowPrimary = DynamicColor(lightHex: 0x5c17e5, lightOpacityHex: 0x33, darkHex: 0xa280ff, darkOpacityHex: 0x33)
    static let accentGlowSecondary = DynamicColor(lightHex: 0x5c17e5, lightOpacityHex: 0x1e, darkHex: 0xa280ff, darkOpacityHex: 0x33)
    static let accentPrimary = DynamicColor(lightHex: 0x5c17e5, darkHex: 0xa17fff)
    static let accentQuaternary = DynamicColor(lightHex: 0x2b097a, darkHex: 0x6e29ee)
    static let accentSecondary = DynamicColor(lightHex: 0x470fbf, darkHex: 0x8f69fb)
    static let accentTertiary = DynamicColor(lightHex: 0x3b0da6, darkHex: 0x7f55f6)
    static let accentTextPrimary = DynamicColor(lightHex: 0x470fbf, darkHex: 0xc6b2ff)
    static let accentTextSecondary = DynamicColor(lightHex: 0x3b0da6, darkHex: 0xa17fff)
    static let accentTextTertiary = DynamicColor(lightHex: 0x2b097a, darkHex: 0x8f69fb)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x0f, darkHex: 0xf5f5fe, darkOpacityHex: 0x16)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x16, darkHex: 0xf5f5fe, darkOpacityHex: 0x1e)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x1e, darkHex: 0xf5f5fe, darkOpacityHex: 0x28)
    static let containerFillPrimary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x02, darkHex: 0xf5f5fe, darkOpacityHex: 0x07)
    static let containerFillSecondary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x07, darkHex: 0xf5f5fe, darkOpacityHex: 0x0f)
    static let containerFillTertiary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x0f, darkHex: 0xf5f5fe, darkOpacityHex: 0x16)
    static let controlsBorderPrimary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x51, darkHex: 0xc0a5fd, darkOpacityHex: 0x7a)
    static let controlsBorderQuaternary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0xb7, darkHex: 0xc0a5fd, darkOpacityHex: 0xcc)
    static let controlsBorderSecondary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x8e, darkHex: 0xc0a5fd, darkOpacityHex: 0xa3)
    static let controlsBorderTertiary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0xa3, darkHex: 0xc0a5fd, darkOpacityHex: 0xb7)
    static let controlsFillPrimary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x16, darkHex: 0xbfa5fc, darkOpacityHex: 0x1e)
    static let controlsFillSecondary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x1e, darkHex: 0xc0a5fd, darkOpacityHex: 0x2d)
    static let controlsFillTertiary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x2d, darkHex: 0xc0a5fd, darkOpacityHex: 0x3d)
    static let controlsRaisedBackdrop = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x16, darkHex: 0xffffff, darkOpacityHex: 0x1e)
    static let controlsRaisedFillPrimary = DynamicColor(lightHex: 0xf6f6fc, darkHex: 0xf3f2fa, darkOpacityHex: 0x2d)
    static let destructiveContentPrimary = DynamicColor(lightHex: 0xffffff, darkHex: 0x000000)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0xe5, darkHex: 0x000000, darkOpacityHex: 0xe5)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x99, darkHex: 0x000000, darkOpacityHex: 0x99)
    static let destructiveGlowPrimary = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x33)
    static let destructiveGlowSecondary = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x1e)
    static let destructivePrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTertiary = DynamicColor(lightHex: 0xaa1826, darkHex: 0xaa1926)
    static let destructiveTextPrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveTextSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTextTertiary = DynamicColor(lightHex: 0xaa1926, darkHex: 0xaa1926)
    static let highlightPrimary = DynamicColor(lightHex: 0xf5f5fe, lightOpacityHex: 0x3d, darkHex: 0xf3f2fa, darkOpacityHex: 0x1e)
    static let iconsPrimary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0xd6, darkHex: 0xefefff, darkOpacityHex: 0xc6)
    static let iconsSecondary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x99, darkHex: 0xf5f5fe, darkOpacityHex: 0x7a)
    static let iconsTertiary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x5b, darkHex: 0xf5f5fe, darkOpacityHex: 0x3d)
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0c, darkHex: 0x000000, darkOpacityHex: 0x28)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x14, darkHex: 0x000000, darkOpacityHex: 0x3d)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x28, darkHex: 0x000000, darkOpacityHex: 0x51)
    static let surfaceBackdrop = DynamicColor(lightHex: 0xc0b9e3, darkHex: 0x120b27)
    static let surfaceCanvas = DynamicColor(lightHex: 0xedecf9, darkHex: 0x271c49)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x16, darkHex: 0xc0a5fd, darkOpacityHex: 0x28)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x33, darkHex: 0xc0a5fd, darkOpacityHex: 0x3d)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0x570bda, lightOpacityHex: 0x51, darkHex: 0xc0a5fd, darkOpacityHex: 0x51)
    static let surfacePrimary = DynamicColor(lightHex: 0xe7e4f5, darkHex: 0x2e2158)
    static let surfaceSecondary = DynamicColor(lightHex: 0xedebf8, darkHex: 0x3a2a63)
    static let surfaceTertiary = DynamicColor(lightHex: 0xf6f6fc, darkHex: 0x433270)
    static let textPrimary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0xf4, darkHex: 0xefefff, darkOpacityHex: 0xf4)
    static let textSecondary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x99, darkHex: 0xf5f5fe, darkOpacityHex: 0xa8)
    static let textTertiary = DynamicColor(lightHex: 0x07050d, lightOpacityHex: 0x5b, darkHex: 0xf5f5fe, darkOpacityHex: 0x5b)
    static let toneShadePrimary = DynamicColor(lightHex: 0x231451, lightOpacityHex: 0x0f, darkHex: 0x0c0915, darkOpacityHex: 0x28)
    static let toneTintPrimary = DynamicColor(lightHex: 0xf5f5fe, lightOpacityHex: 0x8e, darkHex: 0xe9e7f8, darkOpacityHex: 0x0f)

    // MARK: - Inherited from FigmaColorPalette

    static let destructiveGlow = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x33)

    // MARK: - Not Specialized

    static let alertGreen = DynamicColor(lightColor: .alertGreen, darkColor: .alertGreen)
    static let alertYellow = DynamicColor(lightColor: .alertYellow, darkColor: .alertYellow)
    static let shieldPrivacy = DynamicColor(lightColor: RebrandingColor.Lilypad.lilypad70, darkColor: RebrandingColor.Lilypad.lilypad50)

    static let buttonsWhite = DynamicColor(lightColor: .white, darkColor: .black)

    static let buttonsPrimaryDefault = DynamicColor(lightColor: .blue50, darkColor: .blue30)
    static let buttonsPrimaryPressed = DynamicColor(lightColor: .blue70, darkColor: .blue50)
    static let buttonsPrimaryDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsPrimaryText = DynamicColor(lightColor: .white, darkColor: .shade(0.84))
    static let buttonsPrimaryTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let buttonsSecondaryFillDefault = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillPressed = DynamicColor(lightColor: .shade(0.18), darkColor: .tint(0.3))
    static let buttonsSecondaryFillDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillText = DynamicColor(lightColor: .shade(0.84), darkColor: .white)
    static let buttonsSecondaryFillTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let lines = DynamicColor(lightHex: 0x1F1F1F, lightOpacity: 0.09, darkHex: 0xF9F9F9, darkOpacity: 0.12)
}

#endif
